  server:
    port: 9001

  eureka:
    instance:
      prefer-ip-address: true
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/


  spring:
    application:
      name: microservice-provider-user
    data:
      mongodb:
        host: localhost


