  server:
    port: 9000

  eureka:
    instance:
      prefer-ip-address: true
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/


  spring:

    application:
      name: microservice-provider-testrecord
    data:
      mongodb:
        username:
        database: beta_db
        password:
        uri: mongodb://localhost


