  server:
    port: 9000

  eureka:
    instance:
      preferIpAddress: true
    client:
      serviceUrl:
        defaultZone: http://discovery:8761/eureka/

  ribbon:
    eureka:
      enabled: true


  spring:
    application:
      name: microservice-provider-testrecord
    data:
      mongodb:
        username:
        database: beta_db
        password:
        uri: mongodb://localhost


