  server:
    port: 9000

  ribbon:
    eureka:
      enabled: true


  spring:
    application:
      name: microservice-provider-testrecord
    data:
      mongodb:
        username:
        database: beta_db
        password:
        uri: mongodb://localhost
