#https://cloud.spring.io/spring-cloud-static/Dalston.SR5/multi/multi__router_and_filter_zuul.html
server:
  port: 8000

spring:
  application:
    name: microservice-gateway-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignoredServices: "*"
  routes:
    project:
      path: /api/project/**
      serviceId: microservice-provider-testrecord
      stripPrefix: false
    branch:
      path: /api/branch/**
      serviceId: microservice-provider-testrecord
      stripPrefix: false
    commit:
      path: /api/commit/**
      serviceId: microservice-provider-testrecord
      stripPrefix: false

#      url: http://localhost:9000
#ribbon:
#  eureka:
#    enabled: true


#

#
