#https://cloud.spring.io/spring-cloud-static/Dalston.SR5/multi/multi__router_and_filter_zuul.html
server:
  port: 8000

spring:
  application:
    name: microservice-gateway-zuul

zuul:
  ignoredServices: "*"
  routes:
    user:
      path: /api/user/**
      serviceId: microservice-provider-user
      stripPrefix: false
    branch:
      path: /api/branch/**
      serviceId: microservice-provider-testrecord
      stripPrefix: false
    commit:
      path: /api/commit/**
      serviceId: microservice-provider-testrecord
      stripPrefix: false
    project:
      path: /api/project/**
      serviceId: microservice-provider-testrecord
      stripPrefix: false
    testrecords:
      path: /api/testrecords/**
      serviceId: microservice-provider-testrecord
      stripPrefix: false

# todo using http://cloud.spring.io/spring-cloud-security/single/spring-cloud-security.html

#      url: http://localhost:9000
#ribbon:
#  eureka:
#    enabled: true
