discovery:
  image: springcloud/discovery
  ports:
    - "8761:8761"
  environment:
    - "SPRING_PROFILES_ACTIVE=dev"
testrecord:
  image: springcloud/testrecord
  ports:
    - "9000:9000"
  links:
    - discovery
  environment:
    - "SPRING_PROFILES_ACTIVE=dev"