discovery:
  image: mobileenerlytics/spring-discovery
  ports:
    - "8761:8761"
  environment:
    - "SPRING_PROFILES_ACTIVE=dev"
testrecord:
  image: mobileenerlytics/spring-testrecord
  ports:
    - "9000:9000"
  links:
    - discovery
  environment:
    - "SPRING_PROFILES_ACTIVE=dev"