discovery:
  image: springcloud/discovery
  ports:
   - "8761:8761"
user:
  image: springcloud/user
  links:
   - discovery
  ports:
  - "10000:10000"
testrecord:
  image: springcloud/testrecord
  links:
   - discovery
  ports:
  - "10001:10001"